services:
  mysql-db-ws:
    image: mysql:8.0
    container_name: mysql-db-ws
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-webservice_db}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge